
import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const NetflixSans = localFont({
  src: [
    {
      path: './fonts/NetflixSans/NetflixSans-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/NetflixSans/NetflixSans-Regular.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/NetflixSans/NetflixSans-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/NetflixSans/NetflixSans-Bold.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  fallback: ['system-ui', 'arial'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body suppressHydrationWarning={true}
          className={`${NetflixSans.className}  antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
